name: Deploy Webiste

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check aws cli
        run: aws --version
      - name: Upload Website
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: eu-central-1
        run: |
          BUCKET_NAME=super-test-bucket-$RANDOM
          # create bucket
          aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1
          # upload index html 
          aws s3 cp index.html s3://$BUCKET_NAME/index.html --acl public-read
          # enable website hosting
          aws s3 website s3://$BUCKET_NAME --index-document index.html
